#' Identification expressions for \theta_{VL_84} (applying IDC algorithm, Shpitser and Pearl, 2006)
#' Expressions derived for G_{main}, G_{alt1}
#' Since 'closed missingness' in G_{main}, missingness indicators are not explicitly included 

library(igraph)
library(causaleffect)


g_vl84_main <- graph.formula(Age -+ CoMo_0,
                             Age -+ CoMo_36,
                             Age -+ CoMo_48,
                             Age -+ CoMo_6,
                             Age -+ CoMo_60,
                             Age -+ CoMo_84,
                             Age -+ NRTI,
                             Age -+ Weight_0,
                             CoMo_0 -+ CoMo_6,
                             CoMo_0 -+ MEMS_6,
                             CoMo_0 -+ VL_6,
                             CoMo_0 -+ Weight_6,
                             CoMo_36 -+ CoMo_48,
                             CoMo_36 -+ MEMS_48,
                             CoMo_36 -+ VL_48,
                             CoMo_36 -+ Weight_48,
                             CoMo_48 -+ CoMo_60,
                             CoMo_48 -+ MEMS_60,
                             CoMo_48 -+ VL_60,
                             CoMo_48 -+ Weight_60,
                             CoMo_6 -+ CoMo_36,
                             CoMo_6 -+ MEMS_36,
                             CoMo_6 -+ VL_36,
                             CoMo_6 -+ Weight_36,
                             CoMo_60 -+ CoMo_84,
                             CoMo_60 -+ MEMS_84,
                             CoMo_60 -+ VL_84,
                             CoMo_60 -+ Weight_84,
                             Dose_36 -+ Dose_48,
                             Dose_36 -+ EFV_36,
                             Dose_48 -+ Dose_60,
                             Dose_48 -+ EFV_48,
                             Dose_6 -+ Dose_36,
                             Dose_6 -+ EFV_6,
                             Dose_60 -+ Dose_84,
                             Dose_60 -+ EFV_60,
                             Dose_84 -+ EFV_84,
                             EFV_36 -+ VL_36,
                             EFV_36 -+ VL_48,
                             EFV_36 -+ VL_60,
                             EFV_36 -+ VL_84,
                             EFV_48 -+ VL_48,
                             EFV_48 -+ VL_60,
                             EFV_48 -+ VL_84,
                             EFV_6 -+ VL_36,
                             EFV_6 -+ VL_48,
                             EFV_6 -+ VL_6,
                             EFV_6 -+ VL_60,
                             EFV_6 -+ VL_84,
                             EFV_60 -+ VL_60,
                             EFV_60 -+ VL_84,
                             EFV_84 -+ VL_84,
                             Genotype -+ EFV_36,
                             Genotype -+ EFV_48,
                             Genotype -+ EFV_6,
                             Genotype -+ EFV_60,
                             Genotype -+ EFV_84,
                             MEMS_36 -+ CoMo_48,
                             MEMS_36 -+ EFV_36,
                             MEMS_36 -+ MEMS_48,
                             MEMS_48 -+ CoMo_60,
                             MEMS_48 -+ EFV_48,
                             MEMS_48 -+ MEMS_60,
                             MEMS_6 -+ CoMo_36,
                             MEMS_6 -+ EFV_6,
                             MEMS_6 -+ MEMS_36,
                             MEMS_60 -+ CoMo_84,
                             MEMS_60 -+ EFV_60,
                             MEMS_60 -+ MEMS_84,
                             MEMS_84 -+ EFV_84,
                             Sex -+ CoMo_0,
                             Sex -+ Genotype,
                             Sex -+ Weight_0,
                             VL_0 -+ VL_6,
                             VL_6 -+ VL_36,
                             VL_36 -+ VL_48,
                             VL_48 -+ VL_60,
                             VL_60 -+ VL_84,
                             VL_0 -+ CoMo_6,
                             VL_6 -+ CoMo_36,
                             VL_36 -+ CoMo_48,
                             VL_48 -+ CoMo_60,
                             VL_60 -+ CoMo_84,
                             Weight_0 -+ CoMo_6,
                             Weight_0 -+ Weight_6,
                             Weight_36 -+ CoMo_48,
                             Weight_36 -+ Dose_36,
                             Weight_36 -+ Weight_48,
                             Weight_48 -+ CoMo_60,
                             Weight_48 -+ Dose_48,
                             Weight_48 -+ Weight_60,
                             Weight_6 -+ CoMo_36,
                             Weight_6 -+ Dose_6,
                             Weight_6 -+ Weight_36,
                             Weight_60 -+ CoMo_84,
                             Weight_60 -+ Dose_60,
                             Weight_60 -+ Weight_84,
                             Weight_84 -+ Dose_84,
                             )


plot(g_vl84_main)

caus_eff_vl84_main <- causal.effect(y = "VL_84", x = c("EFV_6", "EFV_36",
                                                  "EFV_48", "EFV_60", "EFV_84"),
                               G = g_vl84_main,
                               steps = FALSE, simp = FALSE, prune = TRUE, expr = TRUE,
                               stop_on_nonid = TRUE)

cat(caus_eff_vl84_main)

################################################################################


g_vl84_alter <- graph.formula(Age -+ CoMo_0,
                              Age -+ CoMo_36,
                              Age -+ CoMo_48,
                              Age -+ CoMo_6,
                              Age -+ CoMo_60,
                              Age -+ CoMo_84,
                              Age -+ NRTI,
                              Age -+ Weight_0,
                              CoMo_0 -+ CoMo_6,
                              CoMo_0 -+ MEMS_6,
                              CoMo_0 -+ VL_6,
                              CoMo_0 -+ Weight_6,
                              CoMo_36 -+ CoMo_48,
                              CoMo_36 -+ MEMS_48,
                              CoMo_36 -+ VL_48,
                              CoMo_36 -+ Weight_48,
                              CoMo_48 -+ CoMo_60,
                              CoMo_48 -+ MEMS_60,
                              CoMo_48 -+ VL_60,
                              CoMo_48 -+ Weight_60,
                              CoMo_6 -+ CoMo_36,
                              CoMo_6 -+ MEMS_36,
                              CoMo_6 -+ VL_36,
                              CoMo_6 -+ Weight_36,
                              CoMo_60 -+ CoMo_84,
                              CoMo_60 -+ MEMS_84,
                              CoMo_60 -+ VL_84,
                              CoMo_60 -+ Weight_84,
                              Dose_36 -+ Dose_48,
                              Dose_36 -+ EFV_36,
                              Dose_48 -+ Dose_60,
                              Dose_48 -+ EFV_48,
                              Dose_6 -+ Dose_36,
                              Dose_6 -+ EFV_6,
                              Dose_60 -+ Dose_84,
                              Dose_60 -+ EFV_60,
                              Dose_84 -+ EFV_84,
                              EFV_36 -+ VL_36,
                              EFV_36 -+ VL_48,
                              EFV_36 -+ VL_60,
                              EFV_36 -+ VL_84,
                              EFV_48 -+ VL_48,
                              EFV_48 -+ VL_60,
                              EFV_48 -+ VL_84,
                              EFV_6 -+ VL_36,
                              EFV_6 -+ VL_48,
                              EFV_6 -+ VL_6,
                              EFV_6 -+ VL_60,
                              EFV_6 -+ VL_84,
                              EFV_60 -+ VL_60,
                              EFV_60 -+ VL_84,
                              EFV_84 -+ VL_84,
                              Genotype -+ EFV_36,
                              Genotype -+ EFV_48,
                              Genotype -+ EFV_6,
                              Genotype -+ EFV_60,
                              Genotype -+ EFV_84,
                              MEMS_36 -+ CoMo_48,
                              MEMS_36 -+ EFV_36,
                              MEMS_36 -+ MEMS_48,
                              MEMS_48 -+ CoMo_60,
                              MEMS_48 -+ EFV_48,
                              MEMS_48 -+ MEMS_60,
                              MEMS_6 -+ CoMo_36,
                              MEMS_6 -+ EFV_6,
                              MEMS_6 -+ MEMS_36,
                              MEMS_60 -+ CoMo_84,
                              MEMS_60 -+ EFV_60,
                              MEMS_60 -+ MEMS_84,
                              MEMS_84 -+ EFV_84,
                              Sex -+ CoMo_0,
                              Sex -+ Genotype,
                              Sex -+ Weight_0,
                              VL_0 -+ VL_6,
                              VL_6 -+ VL_36,
                              VL_36 -+ VL_48,
                              VL_48 -+ VL_60,
                              VL_60 -+ VL_84,
                              VL_0 -+ CoMo_6,
                              VL_6 -+ CoMo_36,
                              VL_36 -+ CoMo_48,
                              VL_48 -+ CoMo_60,
                              VL_60 -+ CoMo_84,
                              Weight_0 -+ CoMo_6,
                              Weight_0 -+ Weight_6,
                              Weight_36 -+ CoMo_48,
                              Weight_36 -+ Dose_36,
                              Weight_36 -+ Weight_48,
                              Weight_48 -+ CoMo_60,
                              Weight_48 -+ Dose_48,
                              Weight_48 -+ Weight_60,
                              Weight_6 -+ CoMo_36,
                              Weight_6 -+ Dose_6,
                              Weight_6 -+ Weight_36,
                              Weight_60 -+ CoMo_84,
                              Weight_60 -+ Dose_60,
                              Weight_60 -+ Weight_84,
                              Weight_84 -+ Dose_84,
                              VL_0 -+ MV_0, VL_6 -+ MV_6, VL_36 -+ MV_36, VL_48 -+ MV_48, VL_60 -+ MV_60, VL_84 -+ MV_84,
                              BMQ -+ MV_0, BMQ -+ MV_6, BMQ -+ MV_36, BMQ -+ MV_48, BMQ -+ MV_60, BMQ -+ MV_84,
                              SES -+ MV_0, SES -+ MV_6, SES -+ MV_36, SES -+ MV_48, SES -+ MV_60, SES -+ MV_84,
                              BHV -+ MV_0, BHV -+ MV_6, BHV -+ MV_36, BHV -+ MV_48, BHV -+ MV_60, BHV -+ MV_84,
                              MV_0 -+ M.VL_0, MV_0 -+ M.Weight_0,
                              TI_0 -+ M.VL_0,
                              MV_6 -+ M.VL_6, MV_6 -+ M.Weight_6, MV_6 -+ M.EFV_6,
                              TI_6 -+ M.VL_6, TI_6 -+ M.EFV_6, TI_6 -+ M.MEMS_6,
                              MV_36 -+ M.VL_36, MV_36 -+ M.Weight_36, MV_36 -+ M.EFV_36,
                              TI_36 -+ M.VL_36, TI_36 -+ M.EFV_36, TI_36 -+ M.MEMS_36,
                              MV_48 -+ M.VL_48, MV_48 -+ M.Weight_48, MV_48 -+ M.EFV_48,
                              TI_48 -+ M.VL_48, TI_48 -+ M.EFV_48, TI_48 -+ M.MEMS_48,
                              MV_60 -+ M.VL_60, MV_60 -+ M.Weight_60, MV_60 -+ M.EFV_60,
                              TI_60 -+ M.VL_60, TI_60 -+ M.EFV_60, TI_60 -+ M.MEMS_60,
                              MV_84 -+ M.VL_84, MV_84 -+ M.Weight_84, MV_84 -+ M.EFV_84,
                              TI_84 -+ M.VL_84, TI_84 -+ M.EFV_84, TI_84 -+ M.MEMS_84
)


plot(g_vl84_alter)

caus_eff_vl84_alter <- causal.effect(y = "VL_84", x = c("EFV_6", "EFV_36",
                                                       "EFV_48", "EFV_60", "EFV_84"),
                                    G = g_vl84_alter,
                                    steps = FALSE, simp = FALSE, prune = TRUE, expr = TRUE,
                                    stop_on_nonid = TRUE)

cat(caus_eff_vl84_alter)
